#spring.application.name=primo-progetto

server:
 port: 8081
#port 8081 perchè nella 8080 c'è phpMyAdmin
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/java?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#jdbc: java database connection | mysql implements jdbc libreria  deve esporre i metodi per collegarsi al database| interfaccia add get
  username: java
  password: java
 jpa:
#java persistenci api
  show-sql: true
#vogliamo leggere l sql
  hibernate:
   ddl-auto: update

